# Generated by Django 6.0.3 on 2026-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('field_of_study', models.CharField(choices=[('ENG', 'Engineering'), ('COM', 'Commerce'), ('ART', 'Arts'), ('BUS', 'Business'), ('MED', 'Medical'), ('LAW', 'Law')], max_length=10)),
                ('enrollment_date', models.DateField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
